from mcpi.minecraft import Minecraft
mc = Minecraft.create()
import time

input("Здравствуйте! Вы выбрали нашу фирму по телепортационным турам в Майнкрафте. Пожалуйста, если вы готовы нажмине клавишу здесь  ")

mc.player.setTilePos(68, 87, 334)
mc.postToChat("Pozaluysta, oplatite tour almaznim blokom postavlennim na steklo")

input("Поставьте блок и нажмите здесь")

if mc.getBlock(69, 87, 332) == 57:
    input("Начинаем тур! Нажмите клавишу здесь ")
    mc.setBlock(69, 87, 332, 0)
    time.sleep(1)
    mc.player.setTilePos(46, 152, 302)
    mc.postToChat("pravda krasivo? seychas mi poedem tuda")
    time.sleep(20)
    mc.player.setTilePos(47, 90, 289)
    mc.postToChat("pogulayte tut")
    time.sleep(40)
    mc.postToChat("obratite vnimanie na sliz. eto batut")
    mc.player.setTilePos(9, 107, 272)
    mc.postToChat("pogulayte vozle taynika")
    time.sleep(30)
    mc.player.setTilePos(8, 105, 280)
    mc.postToChat("mi seycas v taynike. proydite v pesseru")
    time.sleep(20)
    mc.player.setTilePos(8, 105, 280)
    mc.postToChat("mozete viprignut na batut")
    time.sleep(15)
    mc.player.setTilePos(-59, 97, 307)
    mc.postToChat("pravda krasivo? seychas mi poedem tuda")
    time.sleep(20)
    mc.player.setTilePos(-58, 76, 292)
    mc.postToChat("pogulayte tut")
    time.sleep(40)
    mc.player.setTilePos(-37, 77, 311)
    time.sleep(20)
    mc.player.setTilePos(-121, 140, 268)
    mc.postToChat("ochen krasivoe mesto")
    time.sleep(50)
    mc.player.setTilePos(-40, 78, 256)
    mc.postToChat("posmotrite naverh")
    time.sleep(20)
    mc.postToChat("mozete idti v peseru")
    time.sleep(20)
    mc.player.setTilePos(-95, 81, 298)
    time.sleep(15)
    mc.player.setTilePos(-80, 73, 295)
    time.sleep(60)
    mc.player.setTilePos(121, 140, 268)
    mc.postToChat("pravda krasivo? no mi tuda ne edem. s zemli vid ne ochen")
    time.sleep(30)
    mc.player.setTilePos(-388, 42, 788)
    mc.postToChat("a eto zabrosennaa sahta. mi gulaem tut dolgo. nikuda ne upadite")
    time.sleep(80)
    mc.player.setTilePos(999, 103, 1016)
    mc.postToChat("kruto?")
    time.sleep(80)
    mc.player.setTilePos(1017, 126, 1024)
    mc.postToChat("super")
    time.sleep(60)
    mc.player.setTilePos(1062, 113, 1027)
    mc.postToChat("ozertso")
    time.sleep(30)
    mc.player.setTilePos(1136, 89, 1008)
    mc.postToChat("i pustina radom")
    time.sleep(50)
    mc.player.setTilePos(1283, 76, 841)
    mc.postToChat("taiga")
    time.sleep(80)
    mc.player.setTilePos(1358, 66, 1054)
    mc.postToChat("savanna")
    time.sleep(80)
    mc.player.setTilePos(1393, 69, 1260)
    mc.postToChat("krasivaa derevna")
    time.sleep(80)
    mc.player.setTilePos(68, 87, 334)
    mc.postToChat("spasibo za polzovanie")